# -*- coding: utf-8 -*-
"""RPwdGen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G1bwOT-CxGZaTHBYej4CkUD8BwaRAL_x
"""

import random
import string

# Prompting user to choose their desired length
length = int(input('Choose a length: '))

# Combine letters and digits
characters = string.ascii_letters + string.digits

# Generate a random password
pwd = ''.join(random.choice(characters) for i in range(length))

print(pwd)

