# -*- coding: utf-8 -*-
"""SimpleCalc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G1bwOT-CxGZaTHBYej4CkUD8BwaRAL_x
"""

num1 = float(input("Enter first number: "))
operator = input("Enter operation (+, -, *, /): ")
num2 = float(input("Enter second number: "))

if operator == '+':
    print(f"Result: {num1 + num2}")
elif operator == '-':
    print(f"Result: {num1 - num2}")
elif operator == '*':
    print(f"Result: {num1 * num2}")
elif operator == '/':
    print(f"Result: {num1 / num2}")
else:
    print("Invalid operation")