# -*- coding: utf-8 -*-
"""ToDoList

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icqZF-BgqTm7jVB5tdKiUH1kKvV5_NW8
"""

tasks = []

while True:
    print("\n1. View Tasks 2. Add Task 3. Delete Task 4. Quit")
    choice = input("Choose an option: ")

    if choice == '1':
        print(tasks if tasks else "No tasks.")
    elif choice == '2':
        tasks.append(input("New task: "))
    elif choice == '3':
        if tasks:
            print(tasks.pop(int(input("Task number to delete: ")) - 1))
        else:
            print("No tasks.")
    elif choice == '4':
        break
    else:
        print("Invalid choice.")

